"""Deterministic confidence scoring (theory doc §7).

Confidence generated by the model is not trustworthy by itself (Gotcha,
verbatim) - this scores based on measurable pipeline facts instead: how
many required fields came back non-null, whether a repair retry was
needed, whether constrained decoding was actually used, and whether
chunked extraction produced conflicting values. Never reads the model's
own self-reported confidence field.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

ConfidenceLevel = Literal["low", "medium", "high"]


@dataclass(frozen=True)
class ConfidenceInputs:
    extracted_fields: dict[str, Any]
    required_fields: list[str]
    used_repair_retry: bool = False
    used_constrained_decoding: bool = True
    had_conflicting_chunks: bool = False


def compute_confidence(inputs: ConfidenceInputs) -> ConfidenceLevel:
    """Starts at "high" and downgrades one level per independent risk factor:

    - any required field came back missing (None)
    - a repair retry was needed to reach a valid result
    - constrained decoding was not used (prompt-only fallback mode)
    - chunked extraction produced conflicting values for some field

    0 risk factors -> high, 1 -> medium, 2+ -> low.
    """
    risk_factors = 0

    missing_required = [f for f in inputs.required_fields if inputs.extracted_fields.get(f) is None]
    if missing_required:
        risk_factors += 1
    if inputs.used_repair_retry:
        risk_factors += 1
    if not inputs.used_constrained_decoding:
        risk_factors += 1
    if inputs.had_conflicting_chunks:
        risk_factors += 1

    if risk_factors == 0:
        return "high"
    if risk_factors == 1:
        return "medium"
    return "low"


def missing_required_fields(inputs: ConfidenceInputs) -> list[str]:
    """Which required fields are missing - useful for review-queue annotations
    (Lab 6), not just the collapsed confidence level.
    """
    return [f for f in inputs.required_fields if inputs.extracted_fields.get(f) is None]
