import httpx
import pytest

from ollama_metadata import get_model_metadata, metadata_to_markdown, parse_show_response

# Fixture shaped like a real Ollama /api/show response for a Qwen2.5-style model.
FIXTURE_SHOW_RESPONSE = {
    "modelfile": "# Modelfile generated by...\nFROM /root/.ollama/models/blobs/sha256:abc123\n",
    "parameters": "stop \"<|im_start|>\"\nstop \"<|im_end|>\"",
    "template": "{{ if .System }}<|im_start|>system\n{{ .System }}<|im_end|>\n{{ end }}...",
    "details": {
        "parent_model": "",
        "format": "gguf",
        "family": "qwen2",
        "families": ["qwen2"],
        "parameter_size": "7.6B",
        "quantization_level": "Q4_K_M",
    },
    "model_info": {
        "general.architecture": "qwen2",
        "general.parameter_count": 7615616512,
        "qwen2.context_length": 32768,
        "qwen2.attention.head_count": 28,
        "qwen2.attention.head_count_kv": 4,
    },
}


class TestParseShowResponse:
    def test_extracts_details_fields(self):
        metadata = parse_show_response("qwen2.5:7b", FIXTURE_SHOW_RESPONSE)
        assert metadata.model == "qwen2.5:7b"
        assert metadata.family == "qwen2"
        assert metadata.parameter_size == "7.6B"
        assert metadata.quantization_level == "Q4_K_M"
        assert metadata.format == "gguf"

    def test_extracts_context_length_from_model_info_dynamic_key(self):
        metadata = parse_show_response("qwen2.5:7b", FIXTURE_SHOW_RESPONSE)
        assert metadata.context_length == 32768

    def test_extracts_template(self):
        metadata = parse_show_response("qwen2.5:7b", FIXTURE_SHOW_RESPONSE)
        assert metadata.template is not None
        assert "im_start" in metadata.template

    def test_handles_missing_details_gracefully(self):
        metadata = parse_show_response("bare-model", {})
        assert metadata.family is None
        assert metadata.parameter_size is None
        assert metadata.quantization_level is None
        assert metadata.context_length is None

    def test_handles_missing_model_info_gracefully(self):
        data = {"details": {"family": "llama"}}
        metadata = parse_show_response("m", data)
        assert metadata.family == "llama"
        assert metadata.context_length is None

    def test_raw_field_preserves_original_response(self):
        metadata = parse_show_response("qwen2.5:7b", FIXTURE_SHOW_RESPONSE)
        assert metadata.raw == FIXTURE_SHOW_RESPONSE


class TestMetadataToMarkdown:
    def test_renders_all_fields(self):
        metadata = parse_show_response("qwen2.5:7b", FIXTURE_SHOW_RESPONSE)
        table = metadata_to_markdown(metadata)
        assert "qwen2.5:7b" in table
        assert "qwen2" in table
        assert "7.6B" in table
        assert "Q4_K_M" in table
        assert "32768" in table

    def test_renders_na_for_missing_fields(self):
        metadata = parse_show_response("bare-model", {})
        table = metadata_to_markdown(metadata)
        assert "n/a" in table


def test_get_model_metadata_raises_httperror_when_unreachable():
    # No Ollama server is expected to be running against this bogus port in CI.
    with pytest.raises(httpx.HTTPError):
        get_model_metadata("qwen2.5:7b", base_url="http://localhost:1", timeout=0.2)
