"""Summarization buffer strategy (theory doc §6).

Older non-sticky groups collapse into one summary Turn, generated by an
injected summarize_fn - the same dependency-injection principle as every
adapter since Module 6 (real usage wraps LLMRuntime.generate(); tests
inject a fake). Always keeps the last 1-2 raw turns even when summarizing
everything before them (Gotcha, verbatim), and finishes with drop_oldest()
as a safety net if the summary itself still doesn't fit - "summarize-then-
truncate" is one composite operation, not summarization OR truncation.
"""

from __future__ import annotations

from typing import Callable

from .token_budget import ConversationBudget, TokenCounterFn, heuristic_token_counter, history_exceeds_budget
from .truncation import drop_oldest, group_is_sticky, group_turns
from .turn import Turn

SummarizeFn = Callable[[list[Turn]], str]


def summarize_then_truncate(
    turns: list[Turn],
    budget: ConversationBudget,
    summarize_fn: SummarizeFn,
    token_counter: TokenCounterFn = heuristic_token_counter,
    keep_last_n_raw: int = 2,
) -> list[Turn]:
    if keep_last_n_raw < 0:
        raise ValueError("keep_last_n_raw must be >= 0")

    if not history_exceeds_budget(turns, budget, token_counter):
        return turns

    groups = group_turns(turns)
    non_sticky_indices = [i for i, g in enumerate(groups) if not group_is_sticky(g)]

    keep_raw_indices = set(non_sticky_indices[-keep_last_n_raw:]) if keep_last_n_raw else set()
    summarize_indices = [i for i in non_sticky_indices if i not in keep_raw_indices]

    if not summarize_indices:
        # Nothing old enough to compress (conversation is short relative to
        # keep_last_n_raw) - fall through to drop_oldest as the only lever left.
        return drop_oldest(turns, budget, token_counter)

    to_summarize = [t for i in summarize_indices for t in groups[i]]
    summary_text = summarize_fn(to_summarize)
    summary_turn = Turn(role="system", content=f"[Earlier conversation summary] {summary_text}")

    result: list[Turn] = []
    inserted_summary = False
    for i, group in enumerate(groups):
        if i in summarize_indices:
            if not inserted_summary:
                result.append(summary_turn)
                inserted_summary = True
            continue
        result.extend(group)

    return drop_oldest(result, budget, token_counter)
